### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by D0T7** [rdnkarchiver/gofile-dl#3]
If two files from two different links have the same name , it crashes because it tries to save the first file to storage and the second file with same name is still in use .

Also if same link is repeated in the input file, the program will crash.

Maybe use set or 
`  if val in list: 
    continue 
  else:
    list.append(val)
`

**Comment by rdnkarchiver** [comment]
@D0T7 Thanks for the report. Can you give me the two links with files with the same name?

**Comment by D0T7** [comment]
https://gofile.io/d/TGMFNT(text file named test.txt)
https://gofile.io/d/aY5TCz(different text file with the same name)

One thing that I seem to have overlooked is that if we don't use --flatten there is no error since all the files are stored in separate folders with unique name.

Anyways , the command I used was:
gofile-dl -o ".\test" --flatten https://gofile.io/d/TGMFNT https://gofile.io/d/aY5TCz

Output error: FileExistsError: [WinError 183] Cannot create a file when that file already exists: '.\\test\\test.txt.temp' -> '.\\test\\test.txt'
